### ISSUE TITLE
Rendering metadata?

### ISSUE THREAD

**Issue by HaoZeke** [ismay/metalsmith-layouts#134]
I'm currently using nunjucks with metalsmith layouts and my markdown files are processed by metalsmith pandoc, however I can't seem to access variables with this setup, any suggestions?

**Comment by ismay** [comment]
Hi @HaoZeke, no sorry, that's difficult for me to judge without looking at your code. However, the unit tests are passing so there doesn't seem to be anything wrong with this library. So you can refer to the readme, and if you're having trouble with your implementation I suggest you use stackoverflow or the metalsmith slack channel. Thanks!
