### ISSUE TITLE
Cannot include a handlebars layout with a partial

### ISSUE THREAD

**Issue by aaronibrahim** [ismay/metalsmith-layouts#142]
I've tried every which way to have a handlebars layout include a handlebars partial and it hasn't worked. 

Here are my setups demonstrating the problem I'm having:

* [Baselined Test Case (without a partial include): working](https://github.com/aaronibrahim/metalsmith-layouts-troubleshooting)

* [Test case with a partial include not working](https://github.com/aaronibrahim/metalsmith-layouts-troubleshooting/tree/layouts-with-partials-at-default-locations)
Please note I've indicated all the different ways I've tried structuring the partial include in the readme.

Thank you in advance for your assistance, and please let me know if there is more code I can put up to demonstrate or troubleshoot the problem.

**Comment by ismay** [comment]
Hi @aaronibrahim, partials are no longer automatically registered by this plugin, so you'll need to use metalsmith-register-partials instead. See the changelog: https://github.com/ismay/metalsmith-layouts/blob/master/CHANGELOG.md#200---january-10-2018

Then it should work.

**Comment by aaronibrahim** [comment]
A note to anyone who might come across this thread, metalsmith-register-partials [wasn't updated to address a breaking change in a later metalsmith release](https://github.com/linclark/metalsmith-register-partials/issues/2#issuecomment-153299083), so @timdp released [metalsmith-discover-partials](https://www.npmjs.com/package/metalsmith-discover-partials) and [metalsmith-discover-helpers](https://www.npmjs.com/package/metalsmith-discover-helpers) and they worked for me.

**Comment by ismay** [comment]
@aaronibrahim Thanks for mentioning those plugins! I didn't know that register-partials no longer worked. I'll add the new plugins to the readme.

**Comment by glen-84** [comment]
@ismay Could you also update the GitHub release description?

**Comment by ismay** [comment]
@glen-84 I might address that later. For now you can refer to the changelog.
